### ISSUE TITLE
input

### ISSUE THREAD

**Issue by elespdn** [CondorCompPhil/collazione#18]
I propose to delete the folder preproc and to use input for the input, it is easier and clearer to only have INPUT and EVAL inside DATA.
That's what I've done in the abstractLemm branch (in a separate commit).
In that branch, it works like this:
file are in nameText/source/*.txt
lemmatise produces xml files inside the same 'sources' dir

Lancelot can be moved to input (?)

**Comment by LucenceIng** [comment]
I agree with that.
I think the lancelot folder should be apart from the two kinds of data : there ara data but also an example of categorized variants done manually. Or may be I can delete it and put the correct files in the correct folder
