### ISSUE TITLE
pie versions

### ISSUE THREAD

**Issue by elespdn** [CondorCompPhil/collazione#7]
I have this warning each time the lemmatisation is launched: "Model models/fro_lemma-pos.tar was serialized with a previous version of `pie`. This might result in issues. Model commit is 4d6ed97, whereas current `pie` commit is 0f6cf19."
But then it works. I guess it is normal because pie evolves, which is good.
So for now there is no error, just a warning.
You have this too, I guess?

**Comment by Jean-Baptiste-Camps** [comment]
Yes, we all have it. It should change when we update the model next time.
